logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.sun: INFO
    org.apache.commons.beanutils: INFO
